---
k3s:
  node_name: "{{ inventory_hostname_short }}"
  version: v1.29.0+k3s1
  server_group: 'k3s_servers'
  storage_group: 'k3s_storage'
  zone_regex: '^k3s(\d\d).*'
  zone_replace: 'rack\1'
  cluster:
    pool:
      - 10.0.2.2-10.0.2.99
  manifests:
    path: '/var/lib/rancher/k3s/server/manifests'
    urls:
      # Essential Prometheus Operator CRDs (the rest are installed with the kube-prometheus-stack helm release)
      - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
        filename: custom-prometheus-podmonitors.yaml
      - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
        filename: custom-prometheus-prometheusrules.yaml
      - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
        filename: custom-prometheus-scrapeconfigs.yaml
      - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
        filename: custom-prometheus-servicemonitors.yaml
      # Gateway API CRDs
      - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v0.7.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
        filename: custom-gatewayapi-gatewayclasses.yaml
      - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v0.7.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
        filename: custom-gatewayapi-gateways.yaml
      - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v0.7.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
        filename: custom-gatewayapi-httproutes.yaml
      - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v0.7.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
        filename: custom-gatewayapi-referencegrants.yaml
      - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v0.7.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
        filename: custom-gatewayapi-tlsroutes.yaml
    templates:
      - custom-metallb-helmchart.yaml.j2
      - custom-metallb-l2.yaml.j2
