---
raspberrypi:
  boot_config:
    file: /boot/config.txt
    add:
      - dtoverlay=hifiberry-dacplus
    replace:
      - find: dtoverlay=vc4-fkms-v3d
        with: dtoverlay=vc4-fkms-v3d,audio=off
      - find: dtoverlay=vc4-kms-v3d
        with: dtoverlay=vc4-kms-v3d,noaudio
    disable:
      - dtparam=audio=on
raspotify:
  deb_path: "https://github.com/dtcooper/raspotify/releases/download/0.45.0/raspotify_0.45.0.librespot.v0.5.0-84d28e8_armhf.deb"
  config_regexp:
    'LIBRESPOT_INITIAL_VOLUME=': 'LIBRESPOT_INITIAL_VOLUME="50"'
    'LIBRESPOT_VOLUME_RANGE=': 'LIBRESPOT_VOLUME_RANGE="80.0"'
