---
- name: Raspberry Pi Setup
  hosts: k3s
  become: true
  roles:
    - raspberrypi
    - raspberrypi/bootconfig
    - raspberrypi/cgroups
    - raspberrypi/k3s
    - raspberrypi/longhorn

- name: K3S
  hosts: k3s
  become: true
  roles:
    - node_exporter
    - k3s

- name: K3S Backup
  hosts: k3s_servers
  become: true
  roles:
    - k3s/backup
