---
- name: Raspberry Pi Setup
  hosts: pwrmon
  become: true
  roles:
    - raspberrypi

- name: Setup
  hosts: pwrmon
  become: true
  roles:
    - influxdb
    - influxdb/backup
    - grafana
    - grafana/backup
