---
- name: Raspberry Pi Setup
  hosts: speakers
  become: true
  roles:
    - raspberrypi
    - raspberrypi/bootconfig

- name: Deploy raspotify
  hosts: speakers
  become: true
  roles:
    - raspotify

- name: Deploy snapserver
  hosts: snapserver
  become: true
  roles:
    - snapcast/server

- name: Deploy snapclient
  hosts: speakers
  become: true
  roles:
    - snapcast/client
