---
- name: Install respotify from repo
  when: raspotify.deb_path is not defined or not raspotify.deb_path
  block:
    - name: Install apt key
      ansible.builtin.apt_key:
        url: https://dtcooper.github.io/raspotify/key.asc
        state: present

    - name: Install apt repo
      ansible.builtin.apt_repository:
        repo: deb https://dtcooper.github.io/raspotify raspotify main
        state: present

    - name: Install raspotify
      ansible.builtin.apt:
        name: raspotify
        state: latest
        update_cache: true

- name: Install respotify from package
  ansible.builtin.apt:
    deb: "{{ raspotify.deb_path }}"
  when: raspotify.deb_path is defined and raspotify.deb_path

- name: Set device name
  ansible.builtin.lineinfile:
    path: /etc/raspotify/conf
    regexp: 'LIBRESPOT_NAME='
    line: LIBRESPOT_NAME="{{ inventory_hostname_short.replace('-', ' ').replace('_', ' ') | title }}"
  notify: Restart raspotify

- name: Set config
  ansible.builtin.lineinfile:
    path: /etc/raspotify/conf
    regexp: "{{ item.key }}"
    line: "{{ item.value }}"
  loop: "{{ raspotify.config_regexp | dict2items }}"
  notify: Restart raspotify
  when: raspotify.config_regexp is defined and raspotify.config_regexp
