---
- name: Create node_exporter text-collectors directory
  ansible.builtin.file:
    path: /var/lib/node_exporter/textfile_collector
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install nvme_metrics requirements
  ansible.builtin.apt:
    name:
      - nvme-cli
      - jq
      - moreutils
    state: present
    install_recommends: true

- name: Install NVME metrics script
  ansible.builtin.copy:
    src: "files/nvme_metrics.sh"
    dest: /usr/local/bin/nvme_metrics
    owner: root
    group: root
    mode: '0755'

- name: Create nvme_metrics cron
  ansible.builtin.copy:
    content: |
      #Ansible: nvme_metrics
      PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
      */1 * * * * root /usr/local/bin/nvme_metrics | sponge /var/lib/node_exporter/textfile_collector/nvme_metrics.prom
    dest: /etc/cron.d/nvme_metrics
    mode: '0644'
