---
- name: Update all
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade packages
  apt:
    name: "*"
    state: latest

- name: Clean cache
  apt:
    autoclean: yes
    autoremove: yes
