---
- name: Update all
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Clean cache
  ansible.builtin.apt:
    autoclean: true
    autoremove: true

- name: Disable swap at boot
  ansible.builtin.command: "{{ item }}"
  with_items:
    - swapoff -a
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - update-rc.d dphys-swapfile disable
  changed_when: false
