---
- name: "Adding lines to {{ raspberrypi.boot_config.file }}"
  ansible.builtin.lineinfile:
    line: '{{ item }}'
    dest: "{{ raspberrypi.boot_config.file }}"
    regexp: "^{{ item }}"
  with_items: '{{ raspberrypi.boot_config.add | default([]) }}'
  notify: Reboot and wait for restart

- name: "Adjusting lines in {{ raspberrypi.boot_config.file }}"
  ansible.builtin.lineinfile:
    line: '{{ item.with }}'
    dest: "{{ raspberrypi.boot_config.file }}"
    regexp: "^{{ item.find }}$"
    backrefs: true
  with_items: '{{ raspberrypi.boot_config.replace | default([]) }}'
  notify: Reboot and wait for restart

- name: "Disabling lines in {{ raspberrypi.boot_config.file }}"
  ansible.builtin.lineinfile:
    line: '#{{ item }}'
    dest: "{{ raspberrypi.boot_config.file }}"
    regexp: "^{{ item }}$"
    backrefs: true
  with_items: '{{ raspberrypi.boot_config.disable | default([]) }}'
  notify: Reboot and wait for restart
