---
- name: Restart Grafana
  ansible.builtin.systemd:
    name: grafana-server.service
    state: restarted

- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
