---
- name: Install snapserver package
  ansible.builtin.apt:
    name: snapserver
    state: latest
    update_cache: true

- name: Update default source
  ansible.builtin.lineinfile:
    path: /etc/snapserver.conf
    regexp: '^source = pipe:\/\/\/tmp\/snapfifo\?name=default$'
    line: source = {{ snapserver.source }}
    backrefs: true
  when: snapserver.source is defined and snapserver.source|length != 0
  notify:
    - Restart snapserver
