---
on:
  push:
    branches:
      - main
  pull_request:

name: run tests
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6
